### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by moonmoonCL** [JCBrouwer/OptimalTextures#1]
Where is the code?

**Comment by JCBrouwer** [comment]
We're working on a re-implementation for a course, it should be finished by April 16th.

**Comment by moonmoonCL** [comment]
Oh, thanks.

**Comment by JCBrouwer** [comment]
Hello @moonmoonCL , just an FYI the code is essentially finished for now. We're just working on the write-up of our results, but we've been able to replicate all the results except for masked texture synthesis. Hope the usage is self explanatory enough.

I might flesh out the help messages a little more and maybe eventually add training for the vgg decoder as well, but I think this will probably be the state of things for a while.

**Comment by moonmoonCL** [comment]
WOW! Thank you for sharing!
I ran the code , and the results were perfect!
